// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAhl2AH1i9p4zdL3ZcvjFfWX8CZPKfXU',
    appId: '1:567011668150:web:d730a7a11defebff5af617',
    messagingSenderId: '567011668150',
    projectId: 'explora-geometry---bmapp',
    authDomain: 'explora-geometry---bmapp.firebaseapp.com',
    storageBucket: 'explora-geometry---bmapp.firebasestorage.app',
    measurementId: 'G-D9TJSHVZX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3TRKWB86eO4WUbUzFCHWK4P3Q2FJ3NRU',
    appId: '1:567011668150:android:53f631fa96504db95af617',
    messagingSenderId: '567011668150',
    projectId: 'explora-geometry---bmapp',
    storageBucket: 'explora-geometry---bmapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPA15GwVgAASFYZVry86W_MIzyyPuKP3c',
    appId: '1:567011668150:ios:9eebb63915714a415af617',
    messagingSenderId: '567011668150',
    projectId: 'explora-geometry---bmapp',
    storageBucket: 'explora-geometry---bmapp.firebasestorage.app',
    iosBundleId: 'com.example.bilingualMathGeometry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPA15GwVgAASFYZVry86W_MIzyyPuKP3c',
    appId: '1:567011668150:ios:9eebb63915714a415af617',
    messagingSenderId: '567011668150',
    projectId: 'explora-geometry---bmapp',
    storageBucket: 'explora-geometry---bmapp.firebasestorage.app',
    iosBundleId: 'com.example.bilingualMathGeometry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoAhl2AH1i9p4zdL3ZcvjFfWX8CZPKfXU',
    appId: '1:567011668150:web:86713cd6be8fd6b15af617',
    messagingSenderId: '567011668150',
    projectId: 'explora-geometry---bmapp',
    authDomain: 'explora-geometry---bmapp.firebaseapp.com',
    storageBucket: 'explora-geometry---bmapp.firebasestorage.app',
    measurementId: 'G-THJ9N9VJE6',
  );
}
